In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
%matplotlib inline

### 读取文本格式数据
- csv文件
- tsv文件
- txt文件
- excel文件

pd.read_csv(filepath)  # 读取文本数据，以逗号分隔

pd.read_table(filepath) # 读取文本数据，以tab制表符分隔

In [3]:
adults = pd.read_csv('data/adults.txt')
adults.head()

,age,workclass,final_weight,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
df = DataFrame({
    'id':np.linspace(1, 100, num=100, dtype=int),
    'age':np.random.randint(18, 25, size=100),
    'height': np.random.randint(150, 240, size=100)
})
df.head()

   age  height  id
0   22     159   1
1   19     191   2
2   24     189   3
3   21     185   4
4   20     231   5

In [11]:
# 将现有的DataFrame的数据保存到csv文件中
df.to_csv('data/persons.csv',
          sep=';',
          mode='a',
          header=False)

In [14]:
pd.read_csv('data/persons.csv', sep=';', index_col='id')

     Unnamed: 0  age  height
id
1             0   22     159
2             1   19     191
3             2   24     189
4             3   21     185
5             4   20     231
6             5   20     233
7             6   23     166
8             7   18     154
9             8   18     222
10            9   19     193
11           10   23     168
12           11   19     194
13           12   19     184
14           13   18     164
15           14   22     230
16           15   21     233
17           16   19     202
18           17   18     170
19           18   19     228
20           19   18     192
21           20   19     182
22           21   24     150
23           22   21     201
24           23   19     179
25           24   22     171
26           25   19     211
27           26   21     229
28           27   21     238
29           28   23     193
30           29   18     231
..          ...  ...     ...
71           70   23     216
72           71   20     185
73           72   24     195
74           73   23     228
75           74   20     203
76           75   19     178
77           76   18     209
78           77   20     159
79           78   23     222
80           79   22     229
81           80   21     232
82           81   23     177
83           82   20     179
84           83   21     185
85           84   22     170
86           85   24     197
87           86   19     151
88           87   20     219
89           88   24     239
90           89   23     207
91           90   18     211
92           91   21     204
93           92   19     182
94           93   18     161
95           94   18     207
96           95   23     222
97           96   24     205
98           97   21     191
99           98   22     163
100          99   18     223

[200 rows x 3 columns]

读取分隔符为 tab制表符的文本数据

In [15]:
pd.read_table('data/seeds.tsv')

     15.26  14.84   0.871  5.763  3.312   2.221   5.22      Kama
0    14.88  14.57  0.8811  5.554  3.333  1.0180  4.956      Kama
1    14.29  14.09  0.9050  5.291  3.337  2.6990  4.825      Kama
2    13.84  13.94  0.8955  5.324  3.379  2.2590  4.805      Kama
3    16.14  14.99  0.9034  5.658  3.562  1.3550  5.175      Kama
4    14.38  14.21  0.8951  5.386  3.312  2.4620  4.956      Kama
5    14.69  14.49  0.8799  5.563  3.259  3.5860  5.219      Kama
6    14.11  14.10  0.8911  5.420  3.302  2.7000  5.000      Kama
7    16.63  15.46  0.8747  6.053  3.465  2.0400  5.877      Kama
8    16.44  15.25  0.8880  5.884  3.505  1.9690  5.533      Kama
9    15.26  14.85  0.8696  5.714  3.242  4.5430  5.314      Kama
10   14.03  14.16  0.8796  5.438  3.201  1.7170  5.001      Kama
11   13.89  14.02  0.8880  5.439  3.199  3.9860  4.738      Kama
12   13.78  14.06  0.8759  5.479  3.156  3.1360  4.872      Kama
13   13.74  14.05  0.8744  5.482  3.114  2.9320  4.825      Kama
14   14.59  14.28  0.8993  5.351  3.333  4.1850  4.781      Kama
15   13.99  13.83  0.9183  5.119  3.383  5.2340  4.781      Kama
16   15.69  14.75  0.9058  5.527  3.514  1.5990  5.046      Kama
17   14.70  14.21  0.9153  5.205  3.466  1.7670  4.649      Kama
18   12.72  13.57  0.8686  5.226  3.049  4.1020  4.914      Kama
19   14.16  14.40  0.8584  5.658  3.129  3.0720  5.176      Kama
20   14.11  14.26  0.8722  5.520  3.168  2.6880  5.219      Kama
21   15.88  14.90  0.8988  5.618  3.507  0.7651  5.091      Kama
22   12.08  13.23  0.8664  5.099  2.936  1.4150  4.961      Kama
23   15.01  14.76  0.8657  5.789  3.245  1.7910  5.001      Kama
24   16.19  15.16  0.8849  5.833  3.421  0.9030  5.307      Kama
25   13.02  13.76  0.8641  5.395  3.026  3.3730  4.825      Kama
26   12.74  13.67  0.8564  5.395  2.956  2.5040  4.869      Kama
27   14.11  14.18  0.8820  5.541  3.221  2.7540  5.038      Kama
28   13.45  14.02  0.8604  5.516  3.065  3.5310  5.097      Kama
29   13.16  13.82  0.8662  5.454  2.975  0.8551  5.056      Kama
..     ...    ...     ...    ...    ...     ...    ...       ...
179  11.41  12.95  0.8560  5.090  2.775  4.9570  4.825  Canadian
180  12.46  13.41  0.8706  5.236  3.017  4.9870  5.147  Canadian
181  12.19  13.36  0.8579  5.240  2.909  4.8570  5.158  Canadian
182  11.65  13.07  0.8575  5.108  2.850  5.2090  5.135  Canadian
183  12.89  13.77  0.8541  5.495  3.026  6.1850  5.316  Canadian
184  11.56  13.31  0.8198  5.363  2.683  4.0620  5.182  Canadian
185  11.81  13.45  0.8198  5.413  2.716  4.8980  5.352  Canadian
186  10.91  12.80  0.8372  5.088  2.675  4.1790  4.956  Canadian
187  11.23  12.82  0.8594  5.089  2.821  7.5240  4.957  Canadian
188  10.59  12.41  0.8648  4.899  2.787  4.9750  4.794  Canadian
189  10.93  12.80  0.8390  5.046  2.717  5.3980  5.045  Canadian
190  11.27  12.86  0.8563  5.091  2.804  3.9850  5.001  Canadian
191  11.87  13.02  0.8795  5.132  2.953  3.5970  5.132  Canadian
192  10.82  12.83  0.8256  5.180  2.630  4.8530  5.089  Canadian
193  12.11  13.27  0.8639  5.236  2.975  4.1320  5.012  Canadian
194  12.80  13.47  0.8860  5.160  3.126  4.8730  4.914  Canadian
195  12.79  13.53  0.8786  5.224  3.054  5.4830  4.958  Canadian
196  13.37  13.78  0.8849  5.320  3.128  4.6700  5.091  Canadian
197  12.62  13.67  0.8481  5.410  2.911  3.3060  5.231  Canadian
198  12.76  13.38  0.8964  5.073  3.155  2.8280  4.830  Canadian
199  12.38  13.44  0.8609  5.219  2.989  5.4720  5.045  Canadian
200  12.67  13.32  0.8977  4.984  3.135  2.3000  4.745  Canadian
201  11.18  12.72  0.8680  5.009  2.810  4.0510  4.828  Canadian
202  12.70  13.41  0.8874  5.183  3.091  8.4560  5.000  Canadian
203  12.37  13.47  0.8567  5.204  2.960  3.9190  5.001  Canadian
204  12.19  13.20  0.8783  5.137  2.981  3.6310  4.870  Canadian
205  11.23  12.88  0.8511  5.140  2.795  4.3250  5.003  Canadian
206  13.20  13.66  0.8883  5.236  3.232  8.3150  5.056  Canadian
207  11.84  13.21  0.8521  5.175  2.836  3.5980  5.044  Canadian
208  12.30  13.34  0.8684  5.243  2.974  5.6370  5.063  Canadian

[209 rows x 8 columns]

In [17]:
pd.read_csv('data/seeds.tsv', sep='\t')

     15.26  14.84   0.871  5.763  3.312   2.221   5.22      Kama
0    14.88  14.57  0.8811  5.554  3.333  1.0180  4.956      Kama
1    14.29  14.09  0.9050  5.291  3.337  2.6990  4.825      Kama
2    13.84  13.94  0.8955  5.324  3.379  2.2590  4.805      Kama
3    16.14  14.99  0.9034  5.658  3.562  1.3550  5.175      Kama
4    14.38  14.21  0.8951  5.386  3.312  2.4620  4.956      Kama
5    14.69  14.49  0.8799  5.563  3.259  3.5860  5.219      Kama
6    14.11  14.10  0.8911  5.420  3.302  2.7000  5.000      Kama
7    16.63  15.46  0.8747  6.053  3.465  2.0400  5.877      Kama
8    16.44  15.25  0.8880  5.884  3.505  1.9690  5.533      Kama
9    15.26  14.85  0.8696  5.714  3.242  4.5430  5.314      Kama
10   14.03  14.16  0.8796  5.438  3.201  1.7170  5.001      Kama
11   13.89  14.02  0.8880  5.439  3.199  3.9860  4.738      Kama
12   13.78  14.06  0.8759  5.479  3.156  3.1360  4.872      Kama
13   13.74  14.05  0.8744  5.482  3.114  2.9320  4.825      Kama
14   14.59  14.28  0.8993  5.351  3.333  4.1850  4.781      Kama
15   13.99  13.83  0.9183  5.119  3.383  5.2340  4.781      Kama
16   15.69  14.75  0.9058  5.527  3.514  1.5990  5.046      Kama
17   14.70  14.21  0.9153  5.205  3.466  1.7670  4.649      Kama
18   12.72  13.57  0.8686  5.226  3.049  4.1020  4.914      Kama
19   14.16  14.40  0.8584  5.658  3.129  3.0720  5.176      Kama
20   14.11  14.26  0.8722  5.520  3.168  2.6880  5.219      Kama
21   15.88  14.90  0.8988  5.618  3.507  0.7651  5.091      Kama
22   12.08  13.23  0.8664  5.099  2.936  1.4150  4.961      Kama
23   15.01  14.76  0.8657  5.789  3.245  1.7910  5.001      Kama
24   16.19  15.16  0.8849  5.833  3.421  0.9030  5.307      Kama
25   13.02  13.76  0.8641  5.395  3.026  3.3730  4.825      Kama
26   12.74  13.67  0.8564  5.395  2.956  2.5040  4.869      Kama
27   14.11  14.18  0.8820  5.541  3.221  2.7540  5.038      Kama
28   13.45  14.02  0.8604  5.516  3.065  3.5310  5.097      Kama
29   13.16  13.82  0.8662  5.454  2.975  0.8551  5.056      Kama
..     ...    ...     ...    ...    ...     ...    ...       ...
179  11.41  12.95  0.8560  5.090  2.775  4.9570  4.825  Canadian
180  12.46  13.41  0.8706  5.236  3.017  4.9870  5.147  Canadian
181  12.19  13.36  0.8579  5.240  2.909  4.8570  5.158  Canadian
182  11.65  13.07  0.8575  5.108  2.850  5.2090  5.135  Canadian
183  12.89  13.77  0.8541  5.495  3.026  6.1850  5.316  Canadian
184  11.56  13.31  0.8198  5.363  2.683  4.0620  5.182  Canadian
185  11.81  13.45  0.8198  5.413  2.716  4.8980  5.352  Canadian
186  10.91  12.80  0.8372  5.088  2.675  4.1790  4.956  Canadian
187  11.23  12.82  0.8594  5.089  2.821  7.5240  4.957  Canadian
188  10.59  12.41  0.8648  4.899  2.787  4.9750  4.794  Canadian
189  10.93  12.80  0.8390  5.046  2.717  5.3980  5.045  Canadian
190  11.27  12.86  0.8563  5.091  2.804  3.9850  5.001  Canadian
191  11.87  13.02  0.8795  5.132  2.953  3.5970  5.132  Canadian
192  10.82  12.83  0.8256  5.180  2.630  4.8530  5.089  Canadian
193  12.11  13.27  0.8639  5.236  2.975  4.1320  5.012  Canadian
194  12.80  13.47  0.8860  5.160  3.126  4.8730  4.914  Canadian
195  12.79  13.53  0.8786  5.224  3.054  5.4830  4.958  Canadian
196  13.37  13.78  0.8849  5.320  3.128  4.6700  5.091  Canadian
197  12.62  13.67  0.8481  5.410  2.911  3.3060  5.231  Canadian
198  12.76  13.38  0.8964  5.073  3.155  2.8280  4.830  Canadian
199  12.38  13.44  0.8609  5.219  2.989  5.4720  5.045  Canadian
200  12.67  13.32  0.8977  4.984  3.135  2.3000  4.745  Canadian
201  11.18  12.72  0.8680  5.009  2.810  4.0510  4.828  Canadian
202  12.70  13.41  0.8874  5.183  3.091  8.4560  5.000  Canadian
203  12.37  13.47  0.8567  5.204  2.960  3.9190  5.001  Canadian
204  12.19  13.20  0.8783  5.137  2.981  3.6310  4.870  Canadian
205  11.23  12.88  0.8511  5.140  2.795  4.3250  5.003  Canadian
206  13.20  13.66  0.8883  5.236  3.232  8.3150  5.056  Canadian
207  11.84  13.21  0.8521  5.175  2.836  3.5980  5.044  Canadian
208  12.30  13.34  0.8684  5.243  2.974  5.6370  5.063  Canadian

[209 rows x 8 columns]

读取excel文件

In [26]:
# index_col 指定哪一列作为行索引
stu = pd.read_excel('data/students.xlsx', index_col='id')
stu.head()

   name  age sex  height(cm)  weight(kg)
id
1    吴果   20   男         165          50
2    李平   33   女         158          45
3    王和   21   男         179          75
4    刘言   27   男         180          80
5    王平   20   女         164          82

In [24]:
stu.index.name = None  # 取消索引的名称

In [25]:
stu.head()

  name  age sex  height(cm)  weight(kg)
1   吴果   20   男         165          50
2   李平   33   女         158          45
3   王和   21   男         179          75
4   刘言   27   男         180          80
5   王平   20   女         164          82

### 读取数据库数据
- 常见的数据库
    - mysql
    - sqlite3
    - oracle
    - sqlserver
    - db2
    - HBase/Hive
    - Spark
- pandas的数据库操作的方法
    - pd.read_sql(sql, connection)  从数据库中读取
    - df.to_sql(connection) 将df的数据写入到数据库中

操作sqlite3数据库
- sqlite3是一个前端保存数据的微型的数据库
- 支持标准的sql语句
- 没有自已的数据类型，根据业务数据类型，读写保持一致即可

导包: sqlite3

In [27]:
import sqlite3

In [28]:
# 连接本地sqlite3的数据库文件, xxx.db
conn = sqlite3.connect('data/persons.db')
print('连接sqlite3数据库成功!')

连接sqlite3数据库成功!

In [29]:
# 创建person表
conn.execute('create table person(id,name,sex,age)')
print('创建表成功!')

创建表成功!

In [30]:
sql = "insert into person values (1, 'disen', '男', 20)"
conn.execute(sql)
sql = "insert into person values (2, 'jack', '男', 21)"
conn.execute(sql)
sql = "insert into person values (3, 'rose', '女', 19)"
conn.execute(sql)
sql = "insert into person values (4, 'mack', '男', 23)"
conn.execute(sql)

In [33]:
# 查询数据
pd.read_sql('select * from person where age >= 21', conn)

   id  name sex  age
0   2  jack   男   21
1   4  mack   男   23

In [37]:
# 按性别统计人数
sql = '''
select sex,
       count(id) as cnt,
       max(age) as h, min(age) l
from person group by sex
'''
pd.read_sql(sql, conn)b

  sex  cnt   h   l
0   女    1  19  19
1   男    3  23  20

### 扩展: MySQL数据库备份与恢复
- 备份
    - 进入cmd命令行
    - 执行命令
        - mysqldump -uroot -proot stu > d:\stu.sql
- 恢复数据库
    - mysql客户端执行source命令
        - mysql -uroot -proot
        - create database stu;
        - 查看数据库的字符集
            - show create database stu;
            - show create table student;
        - use stu;
        - source d:\stu.sql

操作mysql数据库
- 连接mysql数据库，返回conn

In [3]:
import pymysql

In [4]:
conn = pymysql.connect(host='127.0.0.1',
                       port=3306,
                       user='root',
                       password='root',
                       db='stu',
                       charset='utf8')
print('连接mysql成功')

连接mysql成功

In [40]:
pd.read_sql('show tables', conn)

  Tables_in_stu
0             A
1        Course
2            SC
3       Student
4       Teacher

In [42]:
pd.read_sql('desc student', conn)

  Field         Type Null Key Default Extra
0    sn  varchar(10)  YES        None
1  name  varchar(10)  YES        None
2   age     datetime  YES        None
3   sex  varchar(10)  YES        None

In [43]:
pd.read_sql('select * from sc', conn)

    sn  cn  score
0   01  01   80.0
1   01  02   90.0
2   01  03   99.0
3   02  01   70.0
4   02  02   60.0
5   02  03   80.0
6   03  01   80.0
7   03  02   80.0
8   03  03   80.0
9   04  01   50.0
10  04  02   30.0
11  04  03   20.0
12  05  01   76.0
13  05  02   87.0
14  06  01   31.0
15  06  03   34.0
16  07  02   89.0
17  07  03   98.0

练习： 查看每一位同学的每门课的成绩
- join on 连接学生表student, 课程表 course

In [46]:
sql="""
select s.sn, s.name sname, c.name cname, sc.score
from student s
join sc on (sc.sn = s.sn)
join course c on (sc.cn = c.cn)
"""
pd.read_sql(sql, conn, index_col='sn')

   sname cname  score
sn
01    赵雷    语文   80.0
01    赵雷    数学   90.0
01    赵雷    英语   99.0
02    钱电    语文   70.0
02    钱电    数学   60.0
02    钱电    英语   80.0
03    孙风    语文   80.0
03    孙风    数学   80.0
03    孙风    英语   80.0
04    李云    语文   50.0
04    李云    数学   30.0
04    李云    英语   20.0
05    周梅    语文   76.0
05    周梅    数学   87.0
06    吴兰    语文   31.0
06    吴兰    英语   34.0
07    郑竹    数学   89.0
07    郑竹    英语   98.0

练习： 1、查询"01"课程比"02"课程成绩高的学生的信息及课程分数
- if 函数 + group by分组语句
- if(条件， True的值, False的值)

In [5]:
sql = """
select s.sn 学号, s.name 姓名, A.c1 课程1, A.c2 课程2
from (
    select
        sn, 
        max(if(cn='01', score, 0)) c1,
        max(if(cn='02', score, 0)) c2
    from sc
    group by sn ) A
join student s on (A.sn = s.sn)
where A.c1 > A.c2 
"""

pd.read_sql(sql, conn)

   学号  姓名   课程1   课程2
0  02  钱电  70.0  60.0
1  04  李云  50.0  30.0
2  06  吴兰  31.0   0.0

In [56]:
create_sql = """
create table c1_c2(
    学号 varchar(20),
    姓名 varchar(50),
    课程1 float,
    课程2 float
)
"""
cursor = conn.cursor()

In [57]:
cursor.execute(create_sql)

0

In [7]:
df2 = pd.read_sql(sql, conn)

In [26]:
# ?? 将df的数据写入到mysql数据库
# 目前仅支持sqlite数据库
from sqlalchemy import create_engine
conn = create_engine('mysql+pymysql://root:root@127.0.0.1/stu?charset=utf8')
df2.to_sql('c1_c2', conn,
           if_exists='replace')

从网络读取数据

In [64]:
url = 'https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv'
pd.read_csv(url)

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2012-12-05,-7426,-6060,-1367,-74,5317,4210,1107,-2183
1,2012-12-12,-8783,-7520,-1263,123,1818,1598,219,-6842
2,2012-12-19,-5496,-5470,-26,-73,103,3472,-3369,-5466
3,2012-12-26,-4451,-4076,-375,550,2610,3333,-722,-1291
4,2013-01-02,-11156,-9622,-1533,-158,2383,2103,280,-8931
5,2013-01-09,14817,7995,6821,2888,9766,7311,2455,27471
6,2014-04-02,3155,938,2217,265,3379,3129,250,6799
7,2014-04-09,5761,2080,3681,1482,1609,1448,161,8852
8,2014-04-16,2286,634,1652,1186,633,604,29,4105
9,2014-04-23,3530,1392,2138,1239,1984,1453,531,6753
10,2014-04-30,-3890,-3996,106,759,888,559,329,-2242
11,2014-05-07,632,-2006,2639,-340,5493,4417,1076,5785
12,2014-05-14,-1079,-2321,1242,1188,4037,3141,897,4146
13,2014-05-21,697,-1790,2487,1216,2196,1398,798,4109
14,2014-05-28,-2453,-2603,150,1108,2041,1236,805,696
15,2014-06-04,2098,-1148,3246,1123,188,-470,658,3409
16,2014-06-11,1236,-1840,3075,1159,2112,1587,524,4506
17,2014-06-18,-922,-2204,1282,1060,4159,3740,419,4297
18,2014-06-25,-93,-1354,1262,1246,3256,2694,562,4409
19,2014-07-02,-7835,-8887,1052,636,2979,2704,276,-4220
20,2014-07-09,666,-1070,1736,1006,2721,3203,-482,4393
21,2014-07-30,118,-1171,1290,1024,1806,1119,687,2949
22,2014-08-06,-471,-3073,2602,-375,-8193,-8658,465,-9040
23,2014-08-13,320,-974,1294,496,1436,539,897,2252
24,2014-08-20,2671,738,1933,821,4999,4185,814,8490
25,2014-08-27,-577,-2199,1623,943,3655,2921,734,4021
26,2014-09-03,-4024,-5305,1281,544,2430,1768,661,-1050
27,2014-09-10,1257,-1291,2548,1055,1554,711,843,3866
28,2014-11-05,-32,-1634,1602,-176,5813,5284,529,5604
29,2014-11-12,1464,61,1403,963,3596,2703,893,6023
30,2014-11-19,-3010,-3622,611,99,2529,1758,771,-383
31,2014-11-25,-1175,-2044,869,-157,2590,1821,769,1258
32,2015-01-07,-3913,-5438,1525,-1057,-3403,-4729,1326,-8373
33,2015-01-14,1774,-37,1811,248,3549,2582,967,5572
34,2015-01-21,1267,856,411,790,1258,220,1038,3315
35,2015-01-28,4343,3455,888,1748,5964,4689,1275,12055
36,2015-02-04,4240,3536,703,793,3237,2274,963,8270
37,2015-02-11,1268,-27,1296,959,5862,5169,693,8089
38,2015-03-04,999,-1933,2932,528,4984,4309,675,6511
39,2015-03-11,3911,-7,3918,851,1298,999,298,6059
40,2015-03-18,1948,-1758,3706,912,452,258,194,3312
41,2015-03-25,-1167,-4478,3311,538,2404,1701,703,1775
42,2015-04-01,-1527,-3307,1780,720,-1296,-1392,96,-2103
43,2015-04-08,1906,-1321,3227,250,1719,1906,-187,3875

读取的csv文件中，如果不存在 header头，则设置header为None

In [67]:
url2 = 'https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/connectionist-bench/sonar/sonar.all-data'
pd.read_csv(url2, header=None)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
5,0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,...,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062,R
6,0.0317,0.0956,0.1321,0.1408,0.1674,0.1710,0.0731,0.1401,0.2083,0.3513,...,0.0201,0.0248,0.0131,0.0070,0.0138,0.0092,0.0143,0.0036,0.0103,R
7,0.0519,0.0548,0.0842,0.0319,0.1158,0.0922,0.1027,0.0613,0.1465,0.2838,...,0.0081,0.0120,0.0045,0.0121,0.0097,0.0085,0.0047,0.0048,0.0053,R
8,0.0223,0.0375,0.0484,0.0475,0.0647,0.0591,0.0753,0.0098,0.0684,0.1487,...,0.0145,0.0128,0.0145,0.0058,0.0049,0.0065,0.0093,0.0059,0.0022,R
9,0.0164,0.0173,0.0347,0.0070,0.0187,0.0671,0.1056,0.0697,0.0962,0.0251,...,0.0090,0.0223,0.0179,0.0084,0.0068,0.0032,0.0035,0.0056,0.0040,R
10,0.0039,0.0063,0.0152,0.0336,0.0310,0.0284,0.0396,0.0272,0.0323,0.0452,...,0.0062,0.0120,0.0052,0.0056,0.0093,0.0042,0.0003,0.0053,0.0036,R
11,0.0123,0.0309,0.0169,0.0313,0.0358,0.0102,0.0182,0.0579,0.1122,0.0835,...,0.0133,0.0265,0.0224,0.0074,0.0118,0.0026,0.0092,0.0009,0.0044,R
12,0.0079,0.0086,0.0055,0.0250,0.0344,0.0546,0.0528,0.0958,0.1009,0.1240,...,0.0176,0.0127,0.0088,0.0098,0.0019,0.0059,0.0058,0.0059,0.0032,R
13,0.0090,0.0062,0.0253,0.0489,0.1197,0.1589,0.1392,0.0987,0.0955,0.1895,...,0.0059,0.0095,0.0194,0.0080,0.0152,0.0158,0.0053,0.0189,0.0102,R
14,0.0124,0.0433,0.0604,0.0449,0.0597,0.0355,0.0531,0.0343,0.1052,0.2120,...,0.0083,0.0057,0.0174,0.0188,0.0054,0.0114,0.0196,0.0147,0.0062,R
15,0.0298,0.0615,0.0650,0.0921,0.1615,0.2294,0.2176,0.2033,0.1459,0.0852,...,0.0031,0.0153,0.0071,0.0212,0.0076,0.0152,0.0049,0.0200,0.0073,R
16,0.0352,0.0116,0.0191,0.0469,0.0737,0.1185,0.1683,0.1541,0.1466,0.2912,...,0.0346,0.0158,0.0154,0.0109,0.0048,0.0095,0.0015,0.0073,0.0067,R
17,0.0192,0.0607,0.0378,0.0774,0.1388,0.0809,0.0568,0.0219,0.1037,0.1186,...,0.0331,0.0131,0.0120,0.0108,0.0024,0.0045,0.0037,0.0112,0.0075,R
18,0.0270,0.0092,0.0145,0.0278,0.0412,0.0757,0.1026,0.1138,0.0794,0.1520,...,0.0084,0.0010,0.0018,0.0068,0.0039,0.0120,0.0132,0.0070,0.0088,R
19,0.0126,0.0149,0.0641,0.1732,0.2565,0.2559,0.2947,0.4110,0.4983,0.5920,...,0.0092,0.0035,0.0098,0.0121,0.0006,0.0181,0.0094,0.0116,0.0063,R
20,0.0473,0.0509,0.0819,0.1252,0.1783,0.3070,0.3008,0.2362,0.3830,0.3759,...,0.0193,0.0118,0.0064,0.0042,0.0054,0.0049,0.0082,0.0028,0.0027,R
21,0.0664,0.0575,0.0842,0.0372,0.0458,0.0771,0.0771,0.1130,0.2353,0.1838,...,0.0141,0.0190,0.0043,0.0036,0.0026,0.0024,0.0162,0.0109,0.0079,R
22,0.0099,0.0484,0.0299,0.0297,0.0652,0.1077,0.2363,0.2385,0.0075,0.1882,...,0.0173,0.0149,0.0115,0.0202,0.0139,0.0029,0.0160,0.0106,0.0134,R
23,0.0115,0.0150,0.0136,0.0076,0.0211,0.1058,0.1023,0.0440,0.0931,0.0734,...,0.0091,0.0016,0.0084,0.0064,0.0026,0.0029,0.0037,0.0070,0.0041,R
24,0.0293,0.0644,0.0390,0.0173,0.0476,0.0816,0.0993,0.0315,0.0736,0.0860,...,0.0035,0.0052,0.0083,0.0078,0.0075,0.0105,0.0160,0.0095,0.0011,R
25,0.0201,0.0026,0.0138,0.0062,0.0133,0.0151,0.0541,0.0210,0.0505,0.1097,...,0.0108,0.0070,0.0063,0.0030,0.0011,0.0007,0.0024,0.0057,0.0044,R
26,0.0151,0.0320,0.0599,0.1050,0.1163,0.1734,0.1679,0.1119,0.0889,0.1205,...,0.0061,0.0015,0.0084,0.0128,0.0054,0.0011,0.0019,0.0023,0.0062,R
27,0.0177,0.0300,0.0288,0.0394,0.0630,0.0526,0.0688,0.0633,0.0624,0.0613,...,0.0102,0.0122,0.0044,0.0075,0.0124,0.0099,0.0057,0.0032,0.0019,R
28,0.0100,0.0275,0.0190,0.0371,0.0416,0.0201,0.0314,0.0651,0.1896,0.2668,...,0.0088,0.0104,0.0036,0.0088,0.0047,0.0117,0.0020,0.0091,0.0058,R
29,0.0189,0.0308,0.0197,0.0622,0.0080,0.0789,0.1440,0.1451,0.1789,0.2522,...,0.0038,0.0096,0.0142,0.0190,0.0140,0.0099,0.0092,0.0052,0.0075,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,0.0197,0.0394,0.0384,0.0076,0.0251,0.0629,0.0747,0.0578,0.1357,0.1695,...,0.0134,0.0097,0.0042,0.0058,0.0072,0.0041,0.0045,0.0047,0.0054,M
179,0.0394,0.0420,0.0446,0.0551,0.0597,0.1416,0.0956,0.0802,0.1618,0.2558,...,0.0146,0.0040,0.0114,0.0032,0.0062,0.0101,0.0068,0.0053,0.0087,M
180,0.0310,0.0221,0.0433,0.0191,0.0964,0.1827,0.1106,0.1702,0.2804,0.4432,...,0.0204,0.0059,0.0053,0.0079,0.0037,0.0015,0.0056,0.0067,0.0054,M
181,0.0423,0.0321,0.0709,0.0108,0.1070,0.0973,0.0961,0.1323,0.2462,0.2696,...,0.0176,0.0035,0.0093,0.0121,0.0075,0.0056,0.0021,0.0043,0.0017,M
182,0.0095,0.0308,0.0539,0.0411,0.0613,0.1039,0.1016,0.1394,0.2592,0.3745,...,0.0181,0.0019,0.0102,0.0133,0.0040,0.0042,0.0030,0.0031,0.0033,M
183,0.0096,0.0404,0.0682,0.0688,0.0887,0.0932,0.0955,0.2140,0.2546,0.2952,...,0.0237,0.0078,0.0144,0.0170,0.0012,0.0109,0.0036,0.0043,0.0018,M
184,0.0269,0.0383,0.0505,0.0707,0.1313,0.2103,0.2263,0.2524,0.3595,0.5915,...,0.0167,0.0199,0.0145,0.0081,0.0045,0.0043,0.0027,0.0055,0.0057,M
185,0.0340,0.0625,0.0381,0.0257,0.0441,0.1027,0.1287,0.1850,0.2647,0.4117,...,0.0141,0.0019,0.0067,0.0099,0.0042,0.0057,0.0051,0.0033,0.0058,M
186,0.0209,0.0191,0.0411,0.0321,0.0698,0.1579,0.1438,0.1402,0.3048,0.3914,...,0.0078,0.0201,0.0104,0.0039,0.0031,0.0062,0.0087,0.0070,0.0042,M
187,0.0368,0.0279,0.0103,0.0566,0.0759,0.0679,0.0970,0.1473,0.2164,0.2544,...,0.0105,0.0024,0.0018,0.0057,0.0092,0.0009,0.0086,0.0110,0.0052,M
188,0.0089,0.0274,0.0248,0.0237,0.0224,0.0845,0.1488,0.1224,0.1569,0.2119,...,0.0096,0.0103,0.0093,0.0025,0.0044,0.0021,0.0069,0.0060,0.0018,M
189,0.0158,0.0239,0.0150,0.0494,0.0988,0.1425,0.1463,0.1219,0.1697,0.1923,...,0.0121,0.0108,0.0057,0.0028,0.0079,0.0034,0.0046,0.0022,0.0021,M
190,0.0156,0.0210,0.0282,0.0596,0.0462,0.0779,0.1365,0.0780,0.1038,0.1567,...,0.0150,0.0060,0.0082,0.0091,0.0038,0.0056,0.0056,0.0048,0.0024,M
191,0.0315,0.0252,0.0167,0.0479,0.0902,0.1057,0.1024,0.1209,0.1241,0.1533,...,0.0108,0.0062,0.0044,0.0072,0.0007,0.0054,0.0035,0.0001,0.0055,M
192,0.0056,0.0267,0.0221,0.0561,0.0936,0.1146,0.0706,0.0996,0.1673,0.1859,...,0.0072,0.0055,0.0074,0.0068,0.0084,0.0037,0.0024,0.0034,0.0007,M
193,0.0203,0.0121,0.0380,0.0128,0.0537,0.0874,0.1021,0.0852,0.1136,0.1747,...,0.0134,0.0094,0.0047,0.0045,0.0042,0.0028,0.0036,0.0013,0.0016,M
194,0.0392,0.0108,0.0267,0.0257,0.0410,0.0491,0.1053,0.1690,0.2105,0.2471,...,0.0083,0.0080,0.0026,0.0079,0.0042,0.0071,0.0044,0.0022,0.0014,M
195,0.0129,0.0141,0.0309,0.0375,0.0767,0.0787,0.0662,0.1108,0.1777,0.2245,...,0.0124,0.0093,0.0072,0.0019,0.0027,0.0054,0.0017,0.0024,0.0029,M
196,0.0050,0.0017,0.0270,0.0450,0.0958,0.0830,0.0879,0.1220,0.1977,0.2282,...,0.0165,0.0056,0.0010,0.0027,0.0062,0.0024,0.0063,0.0017,0.0028,M
197,0.0366,0.0421,0.0504,0.0250,0.0596,0.0252,0.0958,0.0991,0.1419,0.1847,...,0.0132,0.0027,0.0022,0.0059,0.0016,0.0025,0.0017,0.0027,0.0027,M
198,0.0238,0.0318,0.0422,0.0399,0.0788,0.0766,0.0881,0.1143,0.1594,0.2048,...,0.0096,0.0071,0.0084,0.0038,0.0026,0.0028,0.0013,0.0035,0.0060,M
199,0.0116,0.0744,0.0367,0.0225,0.0076,0.0545,0.1110,0.1069,0.1708,0.2271,...,0.0141,0.0103,0.0100,0.0034,0.0026,0.0037,0.0044,0.0057,0.0035,M
200,0.0131,0.0387,0.0329,0.0078,0.0721,0.1341,0.1626,0.1902,0.2610,0.3193,...,0.0150,0.0076,0.0032,0.0037,0.0071,0.0040,0.0009,0.0015,0.0085,M
201,0.0335,0.0258,0.0398,0.0570,0.0529,0.1091,0.1709,0.1684,0.1865,0.2660,...,0.0120,0.0039,0.0053,0.0062,0.0046,0.0045,0.0022,0.0005,0.0031,M
202,0.0272,0.0378,0.0488,0.0848,0.1127,0.1103,0.1349,0.2337,0.3113,0.3997,...,0.0091,0.0045,0.0043,0.0043,0.0098,0.0054,0.0051,0.0065,0.0103,M
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [70]:
pd.read_csv('data/testSet.txt', sep='\t', header=None)

           0          1  2
0  -0.017612  14.053064  0
1  -1.395634   4.662541  1
2  -0.752157   6.538620  0
3  -1.322371   7.152853  0
4   0.423363  11.054677  0
5   0.406704   7.067335  1
6   0.667394  12.741452  0
7  -2.460150   6.866805  1
8   0.569411   9.548755  0
9  -0.026632  10.427743  0
10  0.850433   6.920334  1
11  1.347183  13.175500  0
12  1.176813   3.167020  1
13 -1.781871   9.097953  0
14 -0.566606   5.749003  1
15  0.931635   1.589505  1
16 -0.024205   6.151823  1
17 -0.036453   2.690988  1
18 -0.196949   0.444165  1
19  1.014459   5.754399  1
20  1.985298   3.230619  1
21 -1.693453  -0.557540  1
22 -0.576525  11.778922  0
23 -0.346811  -1.678730  1
24 -2.124484   2.672471  1
25  1.217916   9.597015  0
26 -0.733928   9.098687  0
27 -3.642001  -1.618087  1
28  0.315985   3.523953  1
29  1.416614   9.619232  0
..       ...        ... ..
70  0.074798  11.023650  0
71 -1.337472   0.468339  1
72 -0.102781  13.763651  0
73 -0.147324   2.874846  1
74  0.518389   9.887035  0
75  1.015399   7.571882  0
76 -1.658086  -0.027255  1
77  1.319944   2.171228  1
78  2.056216   5.019981  1
79 -0.851633   4.375691  1
80 -1.510047   6.061992  0
81 -1.076637  -3.181888  1
82  1.821096  10.283990  0
83  3.010150   8.401766  1
84 -1.099458   1.688274  1
85 -0.834872  -1.733869  1
86 -0.846637   3.849075  1
87  1.400102  12.628781  0
88  1.752842   5.468166  1
89  0.078557   0.059736  1
90  0.089392  -0.715300  1
91  1.825662  12.693808  0
92  0.197445   9.744638  0
93  0.126117   0.922311  1
94 -0.679797   1.220530  1
95  0.677983   2.556666  1
96  0.761349  10.693862  0
97 -2.168791   0.143632  1
98  1.388610   9.341997  0
99  0.317029  14.739025  0

[100 rows x 3 columns]